name: Create Release

on:
  push:
    paths:
      - VERSION
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: juliangruber/read-file-action@v1
        id: version
        with:
          path: ./VERSION

          text: ${{ steps.version.outputs.content }}
          regex: '```[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]```'

      - run: |
          tag=${{ steps.version.outputs.content }}
          message='${{ steps.version.outputs.content }}'
          [[ ${tag} =~ ^[0-9]+(\.[0-9]+)*(_QA)?$ ]] || exit 1
          git config user.name "Ezequiel Garcia"
          git config user.email "ezequiel@vanguardiasur.com.ar"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
