name: Create Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: juliangruber/read-file-action@v1
        id: version
        with:
          path: ./VERSION

      - name: Echo version
        run: echo "${{ steps.version.outputs.content }}"

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        if: ${{ steps.version.outputs.content != null }}
        with:
          text: ${{ steps.version.outputs.content }}
          regex: '```[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]```'

      - name: Tagger boy
        run: |
          tag=${{ steps.version.outputs.content }}
          message='${{ steps.version.outputs.content }}'
          git config user.name "Ezequiel Garcia"
          git config user.email "ezequiel@vanguardiasur.com.ar"
          git tag -a "${tag}" -m "${message}"
          git push origin "${tag}"
